app = "nonah"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
