app = "nonah"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"
[build.args]
    CACHE_BUST = "2025-05-10"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

   [[services.ports]]
    port = 8080
    handlers = ["http"]
  [[services.ports]]
    port = 8080
    handlers = ["tls", "http"]
